config/routes.rb
Ariane::Application.routes.draw do

  namespace :administration do
    resources :colors
    resources :categories
    resources :models
    resources :photos
  end

  resources :categories

  resources :models do
    resources :photos
  end

  match 'administration/photos/delete' => 'administration/photos#batch_destroy', :as => :delete_photos
  match 'models/:name/slideshow' => 'models#slideshow', :as => :slideshow

  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "administration/login", :to => "devise/sessions#new"
    get "administration/signup", :to => "devise/registrations#new"
  end

  devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :sign_up => 'signup' }

  root :to => 'categories#index'

end

app/models/administration.rb
module Administration
  def self.table_name_prefix
    'administration_'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :models
  attr_accessible :name

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :name
  validates_uniqueness_of :name
  validates_presence_of :name, :on => :create
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to  :category
  has_many :photos, :dependent => :destroy

  belongs_to :hair_color, class_name: "Color"
  belongs_to :eyes_color, class_name: "Color"

  accepts_nested_attributes_for :photos
  #, :reject_if => proc { |attributes| attributes['photo']['image']['image_file_size'].blank? }

  attr_accessible :name, :category_id, :photos_attributes, :height, :suit, :neck, :shoe, :waist, :size, :bust, :hips, :hair_color_id, :eyes_color_id

  validates_uniqueness_of :name
  validates_presence_of :name, :on => :create

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  has_attached_file :image,
                    :styles => { :cover => ["119x170#", :jpg], :thumb => ["60x40", :jpg],
                                 :medium => ["x106", :jpg], :large => ["600x400", :jpg]
                                },
                    :convert_options => { :medium => "-resize 'x106'",
                                          :large => "-resize '600x400' -background '#eee' \
                                          -gravity center -extent '600x400' -quality 55",
                                          :cover => "-resize '119x170' -background '#eee'\
                                          -gravity center -quality 55",
                                          :thumb => "-resize '60x40' -background '#eee' \
                                          -gravity center -extent '60x40' -quality 55"
                                        },
      #:path => ":rails_root/public/system/:id/:style/:basename.:extension"
      #:path => ":rails_root/public/:attachment/:id/:style/:basename.:extension",
      #:url => "/:attachment/:id/:style/:basename.:extension"
      :path => ":rails_root/public/:attachment/:hash.:extension",
      :url => "/:attachment/:hash.:extension",
      :hash_data => ":class/:attachment/:id/:style/:updated_at",
      :hash_secret => "3Y114164bW3347Fz7C4u4SQ86douka"

  validates_attachment_size :image, :less_than => 4.megabytes
  validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

  belongs_to :model
  attr_accessible :model_id, :name, :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
         #:recoverable, :rememberable, :registerable,

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/administration/models_controller.rb
class Administration::ModelsController < ApplicationController
  before_filter :authenticate_user!
  # GET /models
  # GET /models.json
  def index
    @models = Model.order(:name).paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @models }
    end
  end

  # GET /models/1
  # GET /models/1.json
  def show
    @model = Model.find(params[:id])
    @photos = @model.photos.paginate(:page => params[:page], :per_page => 10)
    @photo = Photo.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/new
  # GET /models/new.json
  def new
    @model = Model.new
#    @model.build_category
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/1/edit
  def edit
    @model = Model.find(params[:id])
  end

  # POST /models
  # POST /models.json
  def create
#    binding.pry
#    params[:model][:category] = Category.find_by_id(params[:model][:category].to_i)
    @model = Model.new(params[:model])
    respond_to do |format|
      if @model.save
        format.html { redirect_to [:administration, @model], notice: 'Model was successfully created.' }
        format.json { render json: @model, status: :created, location: @model }
      else
        format.html { render action: "new" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /models/1
  # PUT /models/1.json
  def update
    @model = Model.find(params[:id])
    respond_to do |format|
      if @model.update_attributes(params[:model])
        format.html { redirect_to [:administration, @model], notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model = Model.find(params[:id])
    @model.destroy

    respond_to do |format|
      format.html { redirect_to administration_models_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController

  def slideshow
    @model = Model.find(params[:name])
    @photos = @model.photos
    @category = Category.find_by_id(@model.category_id)
  end

  # GET /models
  # GET /models.json
  def index
    #@models = Model.all
    @categories = Category.all
    respond_to do |format|
      format.html # index.html.erb
    #  format.json { render json: @models }
    end
  end

  # GET /models/1
  # GET /models/1.json
  def show
    @model = Model.find(params[:id])
    @category = @model.category
    if request.path != model_path(@model)
      redirect_to @model, status: :moved_permanently
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/new
  # GET /models/new.json
  def new
    @model = Model.new
#    @model.build_category
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/1/edit
  def edit
    @model = Model.find(params[:id])
  end

  # POST /models
  # POST /models.json
  def create
#    binding.pry
#    params[:model][:category] = Category.find_by_id(params[:model][:category].to_i)
    @model = Model.new(params[:model])
    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render json: @model, status: :created, location: @model }
      else
        format.html { render action: "new" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /models/1
  # PUT /models/1.json
  def update
    @model = Model.find(params[:id])

    respond_to do |format|
      if @model.update_attributes(params[:model])
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model = Model.find(params[:id])
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/administration/models_helper.rb
module Administration::ModelsHelper
end

app/helpers/models_helper.rb
module ModelsHelper

  def model_info model
    if current_user
      s = "<h3 class=\"center\"> #{link_to raw("<i class='icon-edit icon-white'></i> Edit infos"), administration_model_path(model),
                class: "btn btn-small btn-warning"}&nbsp;&nbsp;#{model.name}:&nbsp;&nbsp;<small>"
    else
      s = "<h3 class=\"center\">#{model.name}:&nbsp;&nbsp;<small>"
    end

    collec = [:hair_color_id, :eyes_color_id]
    attributes = [:height, :suit, :neck, :shoe, :waist, :size, :bust, :hips ]

    model.attributes.each_pair do |attr, value|
      if attributes.index(attr.to_sym)
        s += "#{attr.capitalize}&nbsp;&nbsp;#{value}&nbsp;&nbsp;|&nbsp;&nbsp;" unless value.blank?
      end
      if collec.index(attr.to_sym)
        s += "#{t(attr.to_sym)}&nbsp;&nbsp;#{Color.find_by_id(value.to_i).name}&nbsp;&nbsp;|&nbsp;&nbsp;" unless value.blank?
      end
    end
    s = "#{s.gsub(/&nbsp;\|[&nbsp;]{2,}$/, "")}</small></h3>"
    return raw(s)
  end
end

app/views/models/_ad_gallery.html.erb
<div id="gallery" class="ad-gallery">
  <div class="ad-image-wrapper">
  </div>
  <div class="ad-controls">
  </div>
  <div class="ad-nav">
    <div class="ad-thumbs">
      <ul class="ad-thumb-list">
        <% @photos.each_with_index do |photo, index| %>
          <li>
            <a href="<%= photo.image.url(:large) %>">
              <%= image_tag photo.image.url(:thumb), :class => "image#{index}",
                :title => "",
                :longdesc => "",
                :alt => "" %>
            </a>
          </li>
        <% end -%>
      </ul>
    </div>
  </div>
</div>

app/views/models/_form.html.erb
<%= simple_form_for @model, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> <%= t ".model" %></legend>

    <%= f.input :name %>
    <%#= f.input :category, :collection => Category.all, :prompt => "Choose a category" %>
    <%= f.association :category %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', models_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/models/_galleria.html.erb
<div id="galleria">
  <% @photos.each_with_index do |photo, index| %>
    <a href="<%= photo.image.url(:large) %>">
      <%= image_tag photo.image.url(:thumb) %>
    </a>
  <% end -%>
</div>

app/views/models/edit.html.erb
<%= render :partial => 'form' %>

app/views/models/index.html.erb
<ul class="nav nav-pills">
  <% @categories.each do |category|  %>
    <li>
      <%= link_to category.name, category_path(category) %>
    </li>
  <% end -%>
</ul>

app/views/models/new.html.erb
<%= render :partial => 'form' %>

app/views/models/show.html.erb
<div class="central-nav">
  <ul class="nav nav-pills">
    <% Category.all.each do |category|  %>
      <li <%=  category.name.upcase == "NEW FACES" ? 'class=active' : "" %>>
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end -%>
  </ul>
</div>
<hr />

<% if @models.nil? %>
  <div class="hero-unit">
    <h2>Sorry, no photos yet :(</h2>
    <hr />
    <p>This model does not have any photos yet. </p>
    <p>Please try again later, or <%= mail_to "contact@ariane.rw", "contact the administrator" %> if you still encounter this issue.</p>
  </div>
<% end -%>

app/views/models/slideshow.html.erb
<%# css 'jquery.ad-gallery.css' %>
<% css 'themes/classic/galleria.classic.css' %>

<%# javascript 'ad_gallery.js' %>
<%# javascript 'jquery.ad-gallery.js' %>

<%# javascript 'jquery.ad-gallery.pack.js' %>

<% javascript "galleria-1.2.7.min.js"  %>
<% javascript "themes/classic/galleria.classic.js" %>
<% javascript "themes/classic/galleria.classic.min.js" %>
<% javascript "galleria.js" %>

<div class="central-nav">
  <ul class="nav nav-pills">
    <% Category.all.each do |category|  %>
      <li <%= raw('class="active"') if @category.id == category.id %> >
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end -%>
  </ul>
</div>
<hr />
<%= model_info @model %>
<br />
<% if @photos.empty? %>
  <div class="hero-unit">
    <h2>Sorry, no photos yet :(</h2>
    <hr />
    <p>This models does not have any photos yet. </p>
    <p>Please try again later, or <%= mail_to "contact@ariane.rw", "contact the administrator" %> if you still encounter this issue.</p>
  </div>
<% else %>
  <%#= render :partial => 'ad_gallery' %>
  <br />
  <br />
  <br />
  <%= render :partial => 'galleria' %>
<% end -%>