config/routes.rb
Ariane::Application.routes.draw do

  namespace :administration do
    resources :colors
    resources :categories
    resources :models
    resources :photos
  end

  resources :categories

  resources :models do
    resources :photos
  end

  match 'administration/photos/delete' => 'administration/photos#batch_destroy', :as => :delete_photos
  match 'models/:name/slideshow' => 'models#slideshow', :as => :slideshow

  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "administration/login", :to => "devise/sessions#new"
    get "administration/signup", :to => "devise/registrations#new"
  end

  devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :sign_up => 'signup' }

  root :to => 'categories#index'

end

app/models/administration.rb
module Administration
  def self.table_name_prefix
    'administration_'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :models
  attr_accessible :name

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :name
  validates_uniqueness_of :name
  validates_presence_of :name, :on => :create
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to  :category
  has_many :photos, :dependent => :destroy

  belongs_to :hair_color, class_name: "Color"
  belongs_to :eyes_color, class_name: "Color"

  accepts_nested_attributes_for :photos
  #, :reject_if => proc { |attributes| attributes['photo']['image']['image_file_size'].blank? }

  attr_accessible :name, :category_id, :photos_attributes, :height, :suit, :neck, :shoe, :waist, :size, :bust, :hips, :hair_color_id, :eyes_color_id

  validates_uniqueness_of :name
  validates_presence_of :name, :on => :create

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  has_attached_file :image,
                    :styles => { :cover => ["119x170#", :jpg], :thumb => ["60x40", :jpg],
                                 :medium => ["x106", :jpg], :large => ["600x400", :jpg]
                                },
                    :convert_options => { :medium => "-resize 'x106'",
                                          :large => "-resize '600x400' -background '#eee' \
                                          -gravity center -extent '600x400' -quality 55",
                                          :cover => "-resize '119x170' -background '#eee'\
                                          -gravity center -quality 55",
                                          :thumb => "-resize '60x40' -background '#eee' \
                                          -gravity center -extent '60x40' -quality 55"
                                        },
      #:path => ":rails_root/public/system/:id/:style/:basename.:extension"
      #:path => ":rails_root/public/:attachment/:id/:style/:basename.:extension",
      #:url => "/:attachment/:id/:style/:basename.:extension"
      :path => ":rails_root/public/:attachment/:hash.:extension",
      :url => "/:attachment/:hash.:extension",
      :hash_data => ":class/:attachment/:id/:style/:updated_at",
      :hash_secret => "3Y114164bW3347Fz7C4u4SQ86douka"

  validates_attachment_size :image, :less_than => 4.megabytes
  validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

  belongs_to :model
  attr_accessible :model_id, :name, :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
         #:recoverable, :rememberable, :registerable,

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/administration/categories_controller.rb
class Administration::CategoriesController < ApplicationController
  before_filter :authenticate_user!
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to [:administration, @category], notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to [:administration, @category], notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to administration_categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/administration/colors_controller.rb
class Administration::ColorsController < ApplicationController
  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colors }
    end
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
    @color = Color.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @color }
    end
  end

  # GET /colors/new
  # GET /colors/new.json
  def new
    @color = Color.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @color }
    end
  end

  # GET /colors/1/edit
  def edit
    @color = Color.find(params[:id])
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(params[:color])

    respond_to do |format|
      if @color.save
        format.html { redirect_to [:administration, @color], notice: 'Color was successfully created.' }
        format.json { render json: [:administration, @color], status: :created, location: @color }
      else
        format.html { render action: "new" }
        format.json { render json: [:administration, @color.errors], status: :unprocessable_entity }
      end
    end
  end

  # PUT /colors/1
  # PUT /colors/1.json
  def update
    @color = Color.find(params[:id])

    respond_to do |format|
      if @color.update_attributes(params[:color])
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: [:administration, @color.errors], status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color = Color.find(params[:id])
    @color.destroy

    respond_to do |format|
      format.html { redirect_to administration_colors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/administration/models_controller.rb
class Administration::ModelsController < ApplicationController
  before_filter :authenticate_user!
  # GET /models
  # GET /models.json
  def index
    @models = Model.order(:name).paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @models }
    end
  end

  # GET /models/1
  # GET /models/1.json
  def show
    @model = Model.find(params[:id])
    @photos = @model.photos.paginate(:page => params[:page], :per_page => 10)
    @photo = Photo.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/new
  # GET /models/new.json
  def new
    @model = Model.new
#    @model.build_category
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/1/edit
  def edit
    @model = Model.find(params[:id])
  end

  # POST /models
  # POST /models.json
  def create
#    binding.pry
#    params[:model][:category] = Category.find_by_id(params[:model][:category].to_i)
    @model = Model.new(params[:model])
    respond_to do |format|
      if @model.save
        format.html { redirect_to [:administration, @model], notice: 'Model was successfully created.' }
        format.json { render json: @model, status: :created, location: @model }
      else
        format.html { render action: "new" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /models/1
  # PUT /models/1.json
  def update
    @model = Model.find(params[:id])
    respond_to do |format|
      if @model.update_attributes(params[:model])
        format.html { redirect_to [:administration, @model], notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model = Model.find(params[:id])
    @model.destroy

    respond_to do |format|
      format.html { redirect_to administration_models_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/administration/photos_controller.rb
class Administration::PhotosController < ApplicationController
  # GET /administration/photos
  # GET /administration/photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /administration/photos/1
  # GET /administration/photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /administration/photos/new
  # GET /administration/photos/new.json
  def new
    @photo = Photo.new
    @model = Model.find_by_id(params[:model_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /administration/photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /administration/photos
  # POST /administration/photos.json
  def create
    @photo = Photo.new(params[:photo])
    if @photo.image_file_size.nil?
      flash[:error] = t(:photo_create_no_file)
    end
    @model = Model.find_by_id(@photo.model_id)
    if @photo.save
      flash[:notice] = t(:photo_create_success)
    else
      flash[:error] = t(:photo_create_not_saved)
    end
    respond_to do |format|
      if flash[:error]
        format.html { redirect_to [:administration, @model] }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { redirect_to [:administration, @model] }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /administration/photos/1
  # PUT /administration/photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: t(:photo_update_success) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administration/photos/1
  # DELETE /administration/photos/1.json
  def batch_destroy
    @model = Model.find_by_id(params[:model_id])
    if params[:photos].blank?
      flash[:error] = t(:administration_photos_batch_destroy_no_photos)
    else
      photos = params[:photos]
      names = []
      photos.each do |photo_id|
        photo = Photo.find_by_id(photo_id)
        names << photo.image_file_name.titleize
        photo.destroy
      end
      flash[:success] = "#{t(:administration_photos_batch_destroy_success)}: #{names.join(' ')}"
    end
    respond_to do |format|
      format.html { redirect_to administration_model_path(@model) }
      format.json { head :no_content }
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController

  def slideshow
    @model = Model.find(params[:name])
    @photos = @model.photos
    @category = Category.find_by_id(@model.category_id)
  end

  # GET /models
  # GET /models.json
  def index
    #@models = Model.all
    @categories = Category.all
    respond_to do |format|
      format.html # index.html.erb
    #  format.json { render json: @models }
    end
  end

  # GET /models/1
  # GET /models/1.json
  def show
    @model = Model.find(params[:id])
    @category = @model.category
    if request.path != model_path(@model)
      redirect_to @model, status: :moved_permanently
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/new
  # GET /models/new.json
  def new
    @model = Model.new
#    @model.build_category
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/1/edit
  def edit
    @model = Model.find(params[:id])
  end

  # POST /models
  # POST /models.json
  def create
#    binding.pry
#    params[:model][:category] = Category.find_by_id(params[:model][:category].to_i)
    @model = Model.new(params[:model])
    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render json: @model, status: :created, location: @model }
      else
        format.html { render action: "new" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /models/1
  # PUT /models/1.json
  def update
    @model = Model.find(params[:id])

    respond_to do |format|
      if @model.update_attributes(params[:model])
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model = Model.find(params[:id])
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/administration/categories_helper.rb
module Administration::CategoriesHelper
end

app/helpers/administration/models_helper.rb
module Administration::ModelsHelper
end

app/helpers/administration/photos_helper.rb
module Administration::PhotosHelper
end

app/helpers/models_helper.rb
module ModelsHelper

  def model_info model
    if current_user
      s = "<h3 class=\"center\"> #{link_to raw("<i class='icon-edit icon-white'></i> Edit infos"), administration_model_path(model),
                class: "btn btn-small btn-warning"}&nbsp;&nbsp;#{model.name}:&nbsp;&nbsp;<small>"
    else
      s = "<h3 class=\"center\">#{model.name}:&nbsp;&nbsp;<small>"
    end

    collec = [:hair_color_id, :eyes_color_id]
    attributes = [:height, :suit, :neck, :shoe, :waist, :size, :bust, :hips ]

    model.attributes.each_pair do |attr, value|
      if attributes.index(attr.to_sym)
        s += "#{attr.capitalize}&nbsp;&nbsp;#{value}&nbsp;&nbsp;|&nbsp;&nbsp;" unless value.blank?
      end
      if collec.index(attr.to_sym)
        s += "#{t(attr.to_sym)}&nbsp;&nbsp;#{Color.find_by_id(value.to_i).name}&nbsp;&nbsp;|&nbsp;&nbsp;" unless value.blank?
      end
    end
    s = "#{s.gsub(/&nbsp;\|[&nbsp;]{2,}$/, "")}</small></h3>"
    return raw(s)
  end
end

app/views/administration/models/_add_photos.html.erb
<%= form_for [:administration, @photo], :html => { :class => 'well form-inline', :multipart => true } do |f| %>
  <span class="large"><strong><%= t ".add-file" %> </strong></span>
  <%= f.hidden_field :model_id, :value => @model.id %>
  <%= f.file_field :image, :label => "test" %>
  <span class="help-inline">&nbsp;</span>
  <%= f.submit t(".btn_upload"), :class => 'btn btn-primary', :disable_with => "Uploading..." %>
<% end %>

app/views/administration/models/_delete_photos.html.erb
<div class="well">
  <div class="btn-group">
    <%= button_tag t(".btn_select"), :class => 'btn' %>
    <%= button_tag t(".btn_unselect"), :class => 'btn' %>
    <%= button_tag t(".btn_delete"), :confirm => t(".confirm"), :class => 'btn btn-danger' %>
  </div>
  <%= form_tag request.url, :method => "GET" do %>
      <%= select_tag "photos[]", "ret"  %>
  <% end -%>
</div>

app/views/administration/models/_display_photos.html.erb
<%= form_tag delete_photos_path do %>
  <%# = render :partial => 'delete_photos' %>
  <%= will_paginate @photos %>
  <%= hidden_field_tag :model_id, @model.id %>
  <ul class="thumbnails">
    <% @photos.each do |photo| %>
      <li class="span2">
        <div class="thumbnail width_119">
          <%#= link_to image_tag("http://placehold.it/170x124", :alt => photo.image_file_name), "", :class => "thumbnail" %>
          <%= link_to image_tag(photo.image.url(:cover), :alt => photo.image_file_name), slideshow_url(@model.id)%>
          <%#= link_to image_tag(photo.image.url(:medium), :alt => photo.image_file_name, :class => "height_106_"), slideshow_url(@model.id), :class => "thumbnail fixed-proportions_" %>
          <div class="caption">
              <%= check_box_tag "photos[]", photo.id, false, :class => "valign-bottom" %>
              <%= photo.image_file_name %>
              <%= number_to_human_size photo.image_file_size %>
          </div>
        </div>
    </li>
  <% end -%>
</ul>
  <div class="well">
    <div class="btn-group">
      <%= button_to_function t(".btn_select"), "selectAll()", :class => 'btn', :id => "select_button" %>
      <%= button_tag t(".btn_delete"), :confirm => t(".confirm"), :class => 'btn btn-danger' %>
    </div>
  </div>
<% end -%>

app/views/administration/models/_form.html.erb
<%= simple_form_for [:administration, @model], :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <fieldset>
    <%= f.input :name %>
    <%#= f.input :category, :collection => Category.all, :prompt => "Choose a category" %>
    <%= f.association :category %>
    <%= f.association :hair_color %>
    <%= f.association :eyes_color %>
    <%= f.input :height %>
    <%= f.input :suit %>
    <%= f.input :neck %>
    <%= f.input :shoe %>
    <%= f.input :waist %>
    <%= f.input :size %>
    <%= f.input :bust %>
    <%= f.input :hips %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', administration_models_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/administration/models/edit.html.erb
<div class="page-header">
  <h2>
    <%= controller.action_name.capitalize %> <%= t ".model" %>
    <%= link_to raw("<i class='icon-upload icon-white'></i> Manage Photos"), administration_model_path(@model), class: "btn btn-success pull-right" %>
  </h2>
</div>
<%= render :partial => 'form' %>

app/views/administration/models/index.html.erb
<div class="page-header">
  <h1>Models
    <%= link_to 'Create a new Model', new_administration_model_path, :class => 'btn btn-primary pull-right' %>
  </h1>
</div>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Created at</th>
      <th width="26%">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= link_to model.name.titleize, administration_model_path(model) %></td>
        <td><%= model.category.name %></td>
        <td><%= model.created_at %></td>
        <td>
          <div class="btn-group">
            <%= link_to "Manage photos", administration_model_path(model), :class => "btn btn-mini" %>
            <%= link_to 'Edit details', edit_administration_model_path(model), :class => 'btn btn-mini' %>
            <%= link_to 'Destroy', administration_model_path(model), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @models %>

app/views/administration/models/new.html.erb
<div class="page-header">
  <h2>
    <%= controller.action_name.capitalize %> <%= t ".model" %>
  </h2>
</div>
<%= render :partial => 'form' %>

app/views/administration/models/show.html.erb
<%= javascript "/assets/generic.js" %>
<div class="page-header">
  <h2>
    <%= @model.name %>
    <div class="btn-group pull-right small">
      <%= link_to raw("<i class='icon-home'></i> Back to Model list"), administration_models_path, :class => 'btn'  %>
      <%= link_to raw("<i class='icon-edit icon-white'></i> Edit model personal infos"), edit_administration_model_path(@model), :class => 'btn btn-success' %>
      <%= link_to raw("<i class='icon-trash icon-white'></i> Delete"), administration_model_path(@model), :method => 'delete', :confirm => t(".confirm_model_del", :model => @model.name), :class => 'btn btn-danger' %>
    </div>
  </h2>
</div>
<%= render :partial => 'add_photos' %>

<%#= image_tag(@model.photos.first.image.url(:thumb), :alt => "test") %>
<%#= image_tag("http://placehold.it/119x170", :alt => "test") %>

<% if @model.photos.empty? %>
  <p><%= t ".no-photo" %></p>
<% else %>
  <%= render :partial => 'display_photos' %>
<% end -%>