config/routes.rb
Ariane::Application.routes.draw do

  namespace :administration do
    resources :colors
    resources :categories
    resources :models
    resources :photos
  end

  resources :categories

  resources :models do
    resources :photos
  end

  match 'administration/photos/delete' => 'administration/photos#batch_destroy', :as => :delete_photos
  match 'models/:name/slideshow' => 'models#slideshow', :as => :slideshow

  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "administration/login", :to => "devise/sessions#new"
    get "administration/signup", :to => "devise/registrations#new"
  end

  devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :sign_up => 'signup' }

  root :to => 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :models
  attr_accessible :name

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

app/controllers/administration/categories_controller.rb
class Administration::CategoriesController < ApplicationController
  before_filter :authenticate_user!
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to [:administration, @category], notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to [:administration, @category], notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to administration_categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @category = Category.all
    @models = Model.order("id DESC").paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    if @category.name.upcase == "NEW FACES"
      @models = Model.order("id DESC").paginate(:page => params[:page], :per_page => 10)
    else
      @models = @category.models.order(:name).paginate(:page => params[:page], :per_page => 10)
    end
    if request.path != category_path(@category)
      redirect_to @category, status: :moved_permanently
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/administration/categories_helper.rb
module Administration::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Category</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', categories_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/categories/edit.html.erb
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<div class="central-nav">
  <ul class="nav nav-pills">
    <% Category.all.each do |category|  %>
      <li <%=  category.name.upcase == "NEW FACES" ? 'class=active' : "" %>>
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end -%>
  </ul>
</div>

<hr />
<% if @models.nil? %>
  <div class="hero-unit">
    <h2>Sorry, no photos yet :(</h2>
    <hr />
    <p>This model does not have any photos yet. </p>
    <p>Please try again later, or <%= mail_to "contact@ariane.rw", "contact the administrator" %> if you still encounter this issue.</p>
  </div>
<% else %>
  <ul class="thumbnails">
    <% @models.each do |model| %>
      <li class="span2">
        <% if model.photos.size > 0 %>
          <%= link_to image_tag(model.photos.first.image.url(:cover), :alt => model.photos.first.image_file_name),
                               slideshow_path(model),
                               :class => "thumbnail width_119" %>
        <% else %>
          <%= link_to image_tag("http://placehold.it/119x170", :alt => model.name), model_path(model), :class => "thumbnail width_119" %>
        <% end -%>
        <div class="caption width_119">
          <%#<p style="text-align: center;">[>= link_to model.name, model_path(model) <]</p>%>
          <p style="text-align: center;"><%= model.name %></p>
        </div>
      </li>
    <% end -%>
  </ul>
  <%= will_paginate @models %>
<% end -%>

app/views/categories/new.html.erb
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<div class="central-nav">
  <ul class="nav nav-pills">
    <% Category.all.each do |category|  %>
      <li <%= raw('class="active"') if @category.id == category.id %> >
        <%= link_to category.name, category_path(category) %>
      </li>
    <% end -%>
  </ul>
</div>
<hr />
<!-- <img src="http://placehold.it/170x124" alt=""> -->

<%#= will_paginate @models %>
<% if @models.empty? %>
  <div class="hero-unit">
    <h2>Sorry, no photos yet :(</h2>
    <hr />
    <p>This category does not have any photos yet. </p>
    <p>Please try again later, or <%= mail_to "contact@ariane.rw", "contact the administrator" %> if you still encounter this issue.</p>
  </div>
<% else %>
  <ul class="thumbnails">
    <% @models.each do |model| %>
      <li class="span2">
        <% if model.photos.size > 0 %>
          <%= link_to image_tag(model.photos.first.image.url(:cover), :alt => model.photos.first.image_file_name), slideshow_url(model), :class => "thumbnail width_119" %>
        <% else %>
          <%= link_to image_tag("http://placehold.it/119x170", :alt => model.name), model_path(model), :class => "thumbnail width_119" %>
        <% end -%>
        <div class="caption width_119">
          <p style="text-align: center;"><%= link_to model.name, model_path(model) %></p>
        </div>
      </li>
    <% end -%>
  </ul>
  <%= will_paginate @models %>
<% end -%>