config/routes.rb
Ariane::Application.routes.draw do

  namespace :administration do
    resources :colors
    resources :categories
    resources :models
    resources :photos
  end

  resources :categories

  resources :models do
    resources :photos
  end

  match 'administration/photos/delete' => 'administration/photos#batch_destroy', :as => :delete_photos
  match 'models/:name/slideshow' => 'models#slideshow', :as => :slideshow

  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "administration/login", :to => "devise/sessions#new"
    get "administration/signup", :to => "devise/registrations#new"
  end

  devise_for :users, :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :sign_up => 'signup' }

  root :to => 'categories#index'

end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Uburanga modeling Agency</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to t(".portfolio"), categories_path %></li>
          <li><%= link_to "Contact", page_path("contact") %></li>
          <li><%= link_to "Open-call", page_path("open-call") %></li>
          <li><%= link_to "About", page_path("about") %></li>
        </ul>
        <% if current_user %>
        <!-- Admin menu -->
          <ul class="nav pull-right">
            <li class="dropdown">
              <a href="#"
                class="dropdown-toggle"
                data-toggle="dropdown">
                <%= current_user.email.downcase %>
                <b class="caret"></b>
              </a>

              <%#=link_to content_tag('b', '', :class => 'caret') + "BOB",
                current_user, :class => "dropdown-toggle", "data-toggle" => "dropdown"
              %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".mgm_categories"), administration_categories_path %></li>
              <li><%= link_to t(".mgm_colors"), administration_colors_path %></li>
              <li><%= link_to t(".mgm_models"), administration_models_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        </ul>
      <% end -%>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uburanga model agency</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <% if controller.class.name == "PagesController" %>
      <%= javascript_include_tag 'mercury.js' %>
      <%= stylesheet_link_tag 'mercury_overrides.css' %>
    <% end -%>
    <%= yield(:head) %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render :partial => 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="row">
          <div class="span10 offset1">
            <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
              <a class="close" data-dismiss="alert">×</a>
              <%= msg %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="span10 offset1">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury', 'mercury_overrides' %>
    <%= javascript_include_tag 'mercury', 'mercury_overrides' %>
  </head>
  <body>
    <script type="text/javascript">
      var saveUrl = null; // Set to the url that you want to save any given page to.
      var options = {
        saveStyle: null,  // 'form', or 'json' (default json)
        saveMethod: null, // 'POST', or 'PUT', (create, vs. update -- default POST)
        visible: null     // if the interface should start visible or not (default true)
      };

      <!-- Mix in any configurations provided through Rails.application.config.mercury_config -->
      <% if Rails.application.config.respond_to?(:mercury_config) %>
        jQuery.extend(Mercury.config, <%= Rails.application.config.mercury_config.to_json.html_safe %>);
      <% end -%>

      <!-- Mix in any options for PageEditor provided through Rails.application.config.mercury_page_editor_config -->
      <% if Rails.application.config.respond_to?(:mercury_page_editor_config) %>
        jQuery.extend(options, <%= Rails.application.config.mercury_page_editor_config.to_json.html_safe %>);
      <% end -%>

      <!-- Instantiate the PageEditor -->
      new Mercury.PageEditor(saveUrl, options);
    </script>
  </body>
</html>